/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi.inventaris;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class UI_Inventaris extends javax.swing.JFrame {

    /**
     * Creates new form UI_Beranda
     */
    public UI_Inventaris() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlSide = new javax.swing.JPanel();
        pnlBeranda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlInventaris = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlPinjam = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PnlPegawai = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        PnlKeluar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(240, 245, 249));

        pnlSide.setBackground(new java.awt.Color(0, 0, 0));
        pnlSide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBeranda.setBackground(new java.awt.Color(0, 0, 0));
        pnlBeranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBerandaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBerandaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBerandaMouseExited(evt);
            }
        });
        pnlBeranda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 245, 249));
        jLabel1.setText("Beranda");
        pnlBeranda.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        pnlSide.add(pnlBeranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 350, 90));

        pnlInventaris.setBackground(new java.awt.Color(0, 0, 0));
        pnlInventaris.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlInventarisMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlInventarisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlInventarisMouseExited(evt);
            }
        });
        pnlInventaris.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 245, 249));
        jLabel2.setText("Inventaris");
        pnlInventaris.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        pnlSide.add(pnlInventaris, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 350, 90));

        pnlPinjam.setBackground(new java.awt.Color(0, 0, 0));
        pnlPinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlPinjamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlPinjamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlPinjamMouseExited(evt);
            }
        });
        pnlPinjam.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 245, 249));
        jLabel3.setText("Pinjam-Kembali");
        pnlPinjam.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        pnlSide.add(pnlPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 350, 90));

        PnlPegawai.setBackground(new java.awt.Color(0, 0, 0));
        PnlPegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PnlPegawaiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PnlPegawaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PnlPegawaiMouseExited(evt);
            }
        });
        PnlPegawai.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 245, 249));
        jLabel4.setText("Pegawai");
        PnlPegawai.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        pnlSide.add(PnlPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 350, 90));

        PnlKeluar.setBackground(new java.awt.Color(0, 0, 0));
        PnlKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PnlKeluarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PnlKeluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PnlKeluarMouseExited(evt);
            }
        });
        PnlKeluar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 245, 249));
        jLabel5.setText("Keluar");
        PnlKeluar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        pnlSide.add(PnlKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 350, 100));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1400, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
        );

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nama", "Nim"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(25);
        jTable1.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pnlSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1372, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlSide, javax.swing.GroupLayout.PREFERRED_SIZE, 1242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1075, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlBerandaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBerandaMouseEntered
        // TODO add your handling code here:
        pnlInventaris.setBackground(Color.GRAY);
        pnlBeranda.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_pnlBerandaMouseEntered

    private void pnlBerandaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBerandaMouseExited
        // TODO add your handling code here:
        pnlInventaris.setBackground(Color.GRAY);
        pnlBeranda.setBackground(Color.black);
    }//GEN-LAST:event_pnlBerandaMouseExited

    private void pnlInventarisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlInventarisMouseEntered
        // TODO add your handling code here:
        pnlInventaris.setBackground(Color.gray);
        pnlBeranda.setBackground(Color.black);
    }//GEN-LAST:event_pnlInventarisMouseEntered

    private void pnlInventarisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlInventarisMouseExited
        // TODO add your handling code here: 
        pnlBeranda.setBackground(Color.black);       
        pnlInventaris.setBackground(Color.GRAY);
    }//GEN-LAST:event_pnlInventarisMouseExited

    private void pnlPinjamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPinjamMouseEntered
        // TODO add your handling code here:
        pnlInventaris.setBackground(Color.GRAY);
        pnlPinjam.setBackground(Color.darkGray);
    }//GEN-LAST:event_pnlPinjamMouseEntered

    private void pnlPinjamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPinjamMouseExited
        // TODO add your handling code here:
        pnlBeranda.setBackground(Color.GRAY);
        pnlPinjam.setBackground(Color.black);
        pnlBeranda.setBackground(Color.black);
    }//GEN-LAST:event_pnlPinjamMouseExited

    private void PnlPegawaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlPegawaiMouseEntered
        // TODO add your handling code here:
        pnlInventaris.setBackground(Color.GRAY);
        PnlPegawai.setBackground(Color.darkGray);        
        pnlBeranda.setBackground(Color.black);
    }//GEN-LAST:event_PnlPegawaiMouseEntered

    private void PnlPegawaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlPegawaiMouseExited
        // TODO add your handling code here:
        pnlInventaris.setBackground(Color.GRAY);
        PnlPegawai.setBackground(Color.BLACK);        
        pnlBeranda.setBackground(Color.black);
    }//GEN-LAST:event_PnlPegawaiMouseExited

    private void PnlKeluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlKeluarMouseEntered
        // TODO add your handling code here:
        pnlInventaris.setBackground(Color.GRAY);
        PnlKeluar.setBackground(Color.darkGray);       
        pnlBeranda.setBackground(Color.black);
    }//GEN-LAST:event_PnlKeluarMouseEntered

    private void PnlKeluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlKeluarMouseExited
        // TODO add your handling code here:
        pnlInventaris.setBackground(Color.GRAY);
        PnlKeluar.setBackground(Color.black);
        pnlBeranda.setBackground(Color.black);
    }//GEN-LAST:event_PnlKeluarMouseExited

    private void PnlKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlKeluarMouseClicked
        // TODO add your handling code here:
        int status=JOptionPane.showConfirmDialog(null,"Apakah anda ingin menutup sistem?","Tutup Aplikasi",JOptionPane.YES_NO_OPTION);
        
        if(status==JOptionPane.YES_OPTION){
        System.exit(0);
        }
    }//GEN-LAST:event_PnlKeluarMouseClicked

    private void pnlBerandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBerandaMouseClicked
        // TODO add your handling code here:
        new UI_Beranda().setVisible(true);
        close();
    }//GEN-LAST:event_pnlBerandaMouseClicked

    private void pnlInventarisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlInventarisMouseClicked
        // TODO add your handling code here:
        new UI_Inventaris().setVisible(true);
        close();
    }//GEN-LAST:event_pnlInventarisMouseClicked

    private void pnlPinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPinjamMouseClicked
        // TODO add your handling code here:
        new UI_PinjamKembali().setVisible(true);
        close();
    }//GEN-LAST:event_pnlPinjamMouseClicked

    private void PnlPegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlPegawaiMouseClicked
        // TODO add your handling code here:
        new UI_Pegawai().setVisible(true);
        close();
    }//GEN-LAST:event_PnlPegawaiMouseClicked

    
     public void close(){
        
        //WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        //Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
        this.setVisible(false);
        this.dispose();
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlKeluar;
    private javax.swing.JPanel PnlPegawai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pnlBeranda;
    private javax.swing.JPanel pnlInventaris;
    private javax.swing.JPanel pnlPinjam;
    private javax.swing.JPanel pnlSide;
    // End of variables declaration//GEN-END:variables
}
