/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi.inventaris;

import java.awt.Color;
import java.util.Base64;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameTitlePane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import sun.security.jca.GetInstance;

/**
 *
 * @author USER
 */
public class UI_Main extends javax.swing.JFrame {
    
        int count=1;
//        Fr_Beranda fr_Beranda;
        
    private static Fr_Beranda single_instance_Beranda =null;
    private static Fr_Inventaris single_instance_Inventaris =null; 
//    private static Fr_Beranda single_instance =null;     
//    private static Fr_Beranda single_instance =null; 
    
    public UI_Main() {
        initComponents();
        jDesktopPane1.add(UI_Main.getInstanceBeranda());
        jDesktopPane1.add(UI_Main.getInstanceInventaris());
    }
    
    
    //static digunakan untuk akses Fr_Beranda tanpa harus membuat objeknya terlebih dahulu
    
    //Buat 1 Objek Beranda 
      public static Fr_Beranda getInstanceBeranda(){
        if(single_instance_Beranda == null){
            single_instance_Beranda = new Fr_Beranda();
        }
        return single_instance_Beranda;
      } 
    //Buat 1 objek Inventaris
      public static Fr_Inventaris getInstanceInventaris(){
        if(single_instance_Inventaris == null){
            single_instance_Inventaris = new Fr_Inventaris();
        }  
          return single_instance_Inventaris;
      }
    //Buat 1 objek Pinjam
      
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        pnlSide = new javax.swing.JPanel();
        pnlBeranda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlInventaris = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlPinjam = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PnlPegawai = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        PnlKeluar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(240, 245, 249));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlSide.setBackground(new java.awt.Color(0, 0, 0));
        pnlSide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBeranda.setBackground(new java.awt.Color(153, 153, 153));
        pnlBeranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBerandaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBerandaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBerandaMouseExited(evt);
            }
        });
        pnlBeranda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 245, 249));
        jLabel1.setText("Beranda");
        pnlBeranda.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        pnlSide.add(pnlBeranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 350, 90));

        pnlInventaris.setBackground(new java.awt.Color(0, 0, 0));
        pnlInventaris.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlInventarisMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlInventarisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlInventarisMouseExited(evt);
            }
        });
        pnlInventaris.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 245, 249));
        jLabel2.setText("Inventaris");
        pnlInventaris.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        pnlSide.add(pnlInventaris, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 350, 90));

        pnlPinjam.setBackground(new java.awt.Color(0, 0, 0));
        pnlPinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlPinjamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlPinjamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlPinjamMouseExited(evt);
            }
        });
        pnlPinjam.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 245, 249));
        jLabel3.setText("Pinjam-Kembali");
        pnlPinjam.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        pnlSide.add(pnlPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 350, 90));

        PnlPegawai.setBackground(new java.awt.Color(0, 0, 0));
        PnlPegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PnlPegawaiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PnlPegawaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PnlPegawaiMouseExited(evt);
            }
        });
        PnlPegawai.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 245, 249));
        jLabel4.setText("Pegawai");
        PnlPegawai.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        pnlSide.add(PnlPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 350, 90));

        PnlKeluar.setBackground(new java.awt.Color(0, 0, 0));
        PnlKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PnlKeluarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PnlKeluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PnlKeluarMouseExited(evt);
            }
        });
        PnlKeluar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 245, 249));
        jLabel5.setText("Keluar");
        PnlKeluar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        pnlSide.add(PnlKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 350, 100));

        jPanel1.add(pnlSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1242));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1400, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 31, 1400, -1));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 774, Short.MAX_VALUE)
        );
        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlBerandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBerandaMouseClicked
        // TODO add your handling code here:
//           Fr_Beranda fr_beranda = new Fr_Beranda();
//           BasicInternalFrameUI bi = (BasicInternalFrameUI)fr_beranda.getUI();
//           //bi.setNorthPane(null);
        
//            fr_Beranda = new Fr_Beranda();
//            jDesktopPane1.add(fr_Beranda);
//            fr_Beranda.setVisible(true);
        
              Fr_Beranda Beranda = UI_Main.getInstanceBeranda();
              BasicInternalFrameUI bi = (BasicInternalFrameUI)Beranda.getUI();
              bi.setNorthPane(null);
              Beranda.setVisible(true);
              Beranda.toFront();
              
              
//           
//        
//        if(count!=1){
//            fr_beranda.close();
//        }
//        count++;
//        
        
        
        
        
       
    }//GEN-LAST:event_pnlBerandaMouseClicked

    private void pnlBerandaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBerandaMouseEntered
        // TODO add your handling code here:
        pnlBeranda.setBackground(Color.gray);
    }//GEN-LAST:event_pnlBerandaMouseEntered

    private void pnlBerandaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBerandaMouseExited
        // TODO add your handling code here:
        pnlBeranda.setBackground(Color.GRAY);
    }//GEN-LAST:event_pnlBerandaMouseExited

    private void pnlInventarisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlInventarisMouseClicked
//        // TODO add your handling code here:

              pnlInventaris.setBackground(Color.GRAY);
              pnlBeranda.setBackground(Color.BLACK);
              Fr_Inventaris Inventaris = UI_Main.getInstanceInventaris();
              BasicInternalFrameUI bi = (BasicInternalFrameUI)Inventaris.getUI();
              bi.setNorthPane(null);
              Inventaris.setVisible(true);
              
              Inventaris.toFront();
    }//GEN-LAST:event_pnlInventarisMouseClicked

    private void pnlInventarisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlInventarisMouseEntered
        // TODO add your handling code here:
        //pnlBeranda.setBackground(Color.GRAY);
        pnlInventaris.setBackground(Color.darkGray);
    }//GEN-LAST:event_pnlInventarisMouseEntered

    private void pnlInventarisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlInventarisMouseExited
        // TODO add your handling code here:
        pnlInventaris.setBackground(Color.black);
    }//GEN-LAST:event_pnlInventarisMouseExited

    private void pnlPinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPinjamMouseClicked
        // TODO add your handling code here:
       // new UI_PinjamKembali().setVisible(true);
       // close();
    }//GEN-LAST:event_pnlPinjamMouseClicked

    private void pnlPinjamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPinjamMouseEntered
        // TODO add your handling code here:
        //pnlBeranda.setBackground(Color.GRAY);
        pnlPinjam.setBackground(Color.darkGray);
    }//GEN-LAST:event_pnlPinjamMouseEntered

    private void pnlPinjamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPinjamMouseExited
        // TODO add your handling code here:
        //pnlBeranda.setBackground(Color.GRAY);
        pnlPinjam.setBackground(Color.black);
    }//GEN-LAST:event_pnlPinjamMouseExited

    private void PnlPegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlPegawaiMouseClicked
        // TODO add your handling code here:
        //new UI_Pegawai().setVisible(true);
        //close();
    }//GEN-LAST:event_PnlPegawaiMouseClicked

    private void PnlPegawaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlPegawaiMouseEntered
        // TODO add your handling code here:
        //pnlBeranda.setBackground(Color.GRAY);
        PnlPegawai.setBackground(Color.darkGray);
    }//GEN-LAST:event_PnlPegawaiMouseEntered

    private void PnlPegawaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlPegawaiMouseExited
        // TODO add your handling code here:
        //pnlBeranda.setBackground(Color.GRAY);
        PnlPegawai.setBackground(Color.BLACK);
    }//GEN-LAST:event_PnlPegawaiMouseExited

    private void PnlKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlKeluarMouseClicked
        // TODO add your handling code here:
        int status=JOptionPane.showConfirmDialog(null,"Apakah anda ingin menutup sistem?","Tutup Aplikasi",JOptionPane.YES_NO_OPTION);

        if(status==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_PnlKeluarMouseClicked

    private void PnlKeluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlKeluarMouseEntered
        // TODO add your handling code here:
        //pnlBeranda.setBackground(Color.GRAY);
        PnlKeluar.setBackground(Color.darkGray);
    }//GEN-LAST:event_PnlKeluarMouseEntered

    private void PnlKeluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlKeluarMouseExited
        // TODO add your handling code here:
        //pnlBeranda.setBackground(Color.GRAY);
        PnlKeluar.setBackground(Color.black);
    }//GEN-LAST:event_PnlKeluarMouseExited
     public void close(){
        
        //WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        //Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
        this.setVisible(false);
        this.dispose();
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UI_Login login = new UI_Login();
                login.setVisible(true);
                       
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlKeluar;
    private javax.swing.JPanel PnlPegawai;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel pnlBeranda;
    private javax.swing.JPanel pnlInventaris;
    private javax.swing.JPanel pnlPinjam;
    private javax.swing.JPanel pnlSide;
    // End of variables declaration//GEN-END:variables
}
